### ISSUE TITLE
Add support for GAP packages

### ISSUE THREAD

**Issue by Alasdair-Macindoe** [Alasdair-Macindoe/parallel-sgrp-gap#4]
**17-07-17 Update** : Problem with loading packages seems to have recurred.  The input and subsequent error is as follows: 

```
gap> LoadPackage("FroidurePin");
#I  froidurepin package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
fail
```

This is the same as what I experienced when trying to load the PackageMaker.

**Comment by markuspf** [comment]
To create a GAP package you can use @fingolfin's PackageMaker: https://github.com/fingolfin/PackageMaker

if you use it and find any issues, please report them at the issue tracker ;)
